name: "Release - Generation"

on:
  push:
    tags:
      # Example: 8.4-gen1
      - 8\.\d+\+gen\d+
      # Example: 8.6.0-alpha1
      - 8\.\d+\-alpha\d+

jobs:
  release_script:
    runs-on: ubuntu-latest
    name: Build release script
    steps:
      - uses: actions/checkout@v4

      - name: echo 1
        run: echo ${GITHUB_REF_NAME}
      - name: echo 2
        run: echo ${GITHUB_REF_NAME} | awk -F '+' '{print $1}'
      - name: echo 3
        run: echo ${GITHUB_REF_NAME} | awk -F '+' '{print $1}' | (IFS=. read major minor patch && echo "MAJOR_VERSION=$major")

      - name: Parse major version number
        id: get-major-version
        run: echo ${GITHUB_REF_NAME} | awk -F '+' '{print $1}' | (IFS=. read major minor patch && echo "MAJOR_VERSION=$major" | tee "$GITHUB_OUTPUT")

      - name: Parse minor version number
        id: get-minor-version
        run: echo ${GITHUB_REF_NAME} | awk -F '+' '{print $1}' | (IFS=. read major minor patch && echo "MINOR_VERSION=$minor" | tee "$GITHUB_OUTPUT")


      - name: get operate assets from monorepo
        if: ${{ steps.get-major-version.outputs.MAJOR_VERSION == 8 && steps.get-minor-version.outputs.MINOR_VERSION >= 5 }}
        run: echo "retrieving assets from camunda/camunda"


      - name: get operate assets from operate
        if: ${{ steps.get-major-version.outputs.MAJOR_VERSION == 8 && steps.get-minor-version.outputs.MINOR_VERSION < 5 }}
        run: echo "retrieving assets from camunda/operate"

      - name: debug
        run: echo ${{ steps.get-major-version.outputs.MAJOR_VERSION }}
      - name: debug2
        run: echo ${{ steps.get-major-version.outputs.MINOR_VERSION }}
